apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vipulwebapp
  name: vipulwebapp
  namespace: vipul-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vipulwebapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vipulwebapp
    spec:
      containers:
      - image: wordpress
        name: wordpress
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: vipulweb-config
        env:
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vipuldb-sec
              key: db_pass
        resources: {}
