apiVersion: v1
data:
  WORDPRESS_DB_USER: vipuluser
  WORDPRESS_DB_DB: vipuldb
  WORDPRESS_DB_HOST: vipuldbsvc #Name of DB service
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: vipulweb-config
  namespace: vipul-ns
